# Generated by Django 3.2 on 2023-07-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20230729_0011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FirstOrder',
            new_name='FirstOrders',
        ),
    ]
