# Generated by Django 3.2 on 2023-07-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_firstorder_firstorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='FirstOrders',
        ),
    ]
