# Generated by Django 3.2 on 2023-07-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20230729_0016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='First_Order',
            new_name='FirstOrder',
        ),
    ]
