# Generated by Django 4.2.3 on 2023-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_restaurantplacediningout_restaurantplacenightlife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantplace',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
