# Generated by Django 4.2.3 on 2023-08-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_restaurantplace_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantplacediningout',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantplacenightlife',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
