# Generated by Django 3.2 on 2023-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_alter_restaurantplacediningout_cuisine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantplacediningout',
            name='restaurant_image',
            field=models.ImageField(upload_to='dining_out/'),
        ),
        migrations.AlterField(
            model_name='restaurantplacenightlife',
            name='restaurant_image',
            field=models.ImageField(upload_to='nightlife/'),
        ),
    ]
