# Generated by Django 4.2.4 on 2023-08-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
