# Generated by Django 3.2 on 2023-08-07 15:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0006_auto_20230729_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('community', 'Community'), ('company', 'Company'), ('culture', 'Culture'), ('technology', 'Technology')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='comments',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
