# Generated by Django 3.2 on 2023-08-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0007_auto_20230807_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
