# Generated by Django 3.2 on 2023-08-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0009_auto_20230807_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(),
        ),
    ]
