# Generated by Django 3.2 on 2023-08-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactblog', '0011_auto_20230808_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='question',
        ),
    ]
